language: python
install:
- pip install -r requirements.txt
- python setup.py install
script:
- pytest
deploy:
  skip_cleanup: true
  provider: pypi
  user: tpoveda
  password:
    secure: gG8JKsWjBe2Z3CBQAH4hsHC/m7mz7O0K4knex01zvPQsO3/Z1LbqfUs1fe6eHYxRFc9axzOsz3SAAzYZLBxScW7yU9V3Ck83CBRWEjB8saHX5Aos4KVVHtep8HoM2kpeaU8bVFzoxFdZ3HHY5hz9sLrAJCuXnLwIwD/fZVNoe46cjK3c6iDrqnNIpeX5yTN/g2vUL9w9JcgQhrMRosgetcGBOlfPPMDhUN1rU+E424SBVCA6PQqcyVRfA25zkUNuDCG1P7S34y6+4PDPgaWac4WLbqAZxKtPv9twzhQoRn0BOb3c9kipfIwZMFTyRZ7O+F7uOioM+YcipdhF1SIB3E64ln6mmUH9Vhq1Kiu/+pP3BR789eoZR5xIE5sbi1WH1TvvWTDfdGp9bw/zyIv0O69wXRBdKdt0R/AuM6gSjQ6DGUXM/x8akVweHLn0LFBTYDLuRZ/aTkunJjy+Db0srQK/PYZDqKxojr4RYO/lS9GHyiSNkR7zKYP9dRZiRjD4PFSpSd7cpYPQ7BXtO0SNvqypX8WDyGXL99ETGD0UiPzgYzjPNUY4YkRwpxJWCW+bkw3d2HLdcan11jnmAZ+G46Rg3pCvwC8NHqwPfWz4oaSuCundCu4LIgyA00cRQr38ZTBsZ8H58OYQ6pwWhs0b8u8OZERPIiYYfz8pDqB5rZQ=
  on:
    branch: master
    tags: true
