language: python
install:
- pip install -r requirements.txt
- python setup.py install
script:
- pytest
deploy:
  skip_cleanup: true
  provider: pypi
  user: tpoveda
  password:
    secure: tJFK2B9Z4v6VteANyjaWTdsJxtdOeISKGE8wpln3BmmJc1pWlP4xrFyywC+V0oKjBhDUoqruZPA4kDOxAuQA6mOxwZ4qhzlylq2mmFoVcpRq1xhRls4ILZdWvZddfuPbCd+FwNuPnLDyeJHgGO+t0inw1oK4+jvop21EoutCyT/QTv9UO1bP+VqDFdF+SNj2drB5ibUifvUPQn4UwE5Uk4vGp48M6uXXZ4s1zfFpaic2luEoto3JNeLxyioMPAy4+MBZ6e7q9NZalnnbv/a6e3uzksbvDHAhQKhM+oL7/ihi3kmmz+u17LUuzhwLSAmPctaMelOzjkVUm9n3y2mz+Lsd2o46KGg/Ci2aOF1zm9Dq4AmzgCzyjc1PYA56FnbDBZ8hhUWgnpno17LnPmSAuc2qTFVcipX3Ro4/pZ0JhsirYBAOdZ+InZBR6E+WFtEtHBbWCvGmCxDllBRL4XgnwcnfNkLApZbkgNdgdgU0BCaZHckfbi0V0OxJoVklIWluBdYqtroCFlAy9MPBYd6mxucXxWNFtnyCpgdhXAfylrmOZlqVNIEWs9CUTmAjHwoGKs8qJAnoqWCnU0tE2lGNQa1i3TGEnqEsoafAIT+tjCGm1SbmgcMKdz7zvBcis5DNOYrmPYSdfzvs9nC0ThdJGGKdmmW7/zMCy75QxnvsyZM=
  on:
    branch: master
    tags: true
