language: python
install:
- pip install -r requirements.txt
- python setup.py install
script:
- pytest
deploy:
  skip_cleanup: true
  provider: pypi
  user: tpoveda
  password:
    secure: r7IomcnB+txatzDSsjixWic4npaRPH/2U3w/x9+/qAYsvxD5KdFO9dB304xQXlMOhmjhYMU99j/sS9qID78xPZJe66rNBJCidjkZPKWWkLo0/7j8jL/JWs9GDec8ie3hYVzH3hgIbP5QtSLY4VxwZirMBEattxd1m1vudgKX12HEyLiu7UWbvAFcyGK/+yQiCTQKa+V+VfUvwzMWodv9VdgUaFBWsI0VCNCjaYPR5ciUYFPgH4VuX8vJVu9qYKNsXhE0Z6TsuPDhVfzLxMs5cQyskdqASvQcu2JY/FD0adMsQKhfYtofnaUyqO0XkAIOrIE8s4x2x4lUj7z5Hf82efCDmMDz5edsx7lKabuUwZPcjAC6oXe9YcQ7O44a1ZLESPcFDtM835NDHe0roulpSY+W9JwDU2HJpG9arefcDKV1RisEQ8Uj44i0kNt93dh0bT2UlkrY3f7MuTxgq5DXCfoIQkIRRmJvmCRadJ0g2q3DrWcZWFKpvT/gbLvjs2rx18puuE4Qkc5LT6FgLwDHx1d9nP70/JNZLnhZ+e8IX7T76bb6V+PuY5QEb4ICpbMlPSsjnWZsEDAJ+gQMqHcaDJhkcwqSlEX+ADkkIK5iWn7wUt4zvkDn3TLxiqb5mL28p1BkDNUnF3i8zRt/ED83IClfmoO23vke67UwvUjwXv4=
  on:
    branch: master
    tags: true
